# Generated by Django 3.0.4 on 2020-03-17 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DinnerPlatter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in USD', max_digits=5)),
                ('size', models.CharField(choices=[('Small', 'Small'), ('Large', 'Large')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pasta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in USD', max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(choices=[('Sicilian', 'Sicilian'), ('Regular', 'Regular')], max_length=20)),
                ('size', models.CharField(choices=[('Small', 'Small'), ('Large', 'Large')], max_length=10)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in USD', max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Salad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in USD', max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='SubExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in USD', max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='PizzaOrder',
            fields=[
                ('pizza_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.Pizza')),
                ('extras', models.CharField(choices=[('CH', 'Cheese'), ('1', '1 Topping'), ('1', '2 Toppings'), ('1', '3 Toppings'), ('SP', 'Special')], default='CH', max_length=15)),
                ('quantity', models.IntegerField(default=1)),
            ],
            bases=('orders.pizza',),
        ),
        migrations.CreateModel(
            name='Sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in USD', max_digits=4)),
                ('size', models.CharField(choices=[('Small', 'Small'), ('Large', 'Large')], max_length=10)),
                ('extras', models.ManyToManyField(blank=True, to='orders.SubExtra')),
            ],
        ),
        migrations.AddField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(to='orders.Topping'),
        ),
    ]
