# Generated by Django 3.0.4 on 2020-03-20 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('small_price', models.DecimalField(decimal_places=2, help_text='Price in USD', max_digits=5)),
                ('big_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price in USD', max_digits=5, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Category')),
            ],
        ),
        migrations.DeleteModel(
            name='DinnerPlatter',
        ),
        migrations.DeleteModel(
            name='Pasta',
        ),
        migrations.RemoveField(
            model_name='pizzaorder',
            name='pizza_ptr',
        ),
        migrations.DeleteModel(
            name='Salad',
        ),
        migrations.RemoveField(
            model_name='sub',
            name='extras',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='price',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='size',
        ),
        migrations.AddField(
            model_name='pizza',
            name='big_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price in USD', max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pizza',
            name='small_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price in USD', max_digits=5),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PizzaOrder',
        ),
        migrations.DeleteModel(
            name='Sub',
        ),
        migrations.DeleteModel(
            name='SubExtra',
        ),
    ]
