# Generated by Django 3.0.4 on 2020-03-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_itemorder_order_pizzaorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price in USD', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Ordering', 'Ordering'), ('Processing', 'Processing'), ('Completed', 'Completed')], max_length=20),
        ),
    ]
