# Generated by Django 3.0.4 on 2020-03-21 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200321_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToppingOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_order_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.PizzaOrder')),
                ('topping_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Topping')),
            ],
        ),
    ]
