# Generated by Django 3.0.4 on 2020-03-21 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_toppingorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='toppingorder',
            name='order_number',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='orders.Order'),
            preserve_default=False,
        ),
    ]
